### ISSUE TITLE
The “struct constructor” hidden cost is inaccurate

### ISSUE THREAD

**Issue by lexi-lambda** [stamourv/optimization-coach#5]
The optimization coach claims that struct construction is expensive and advises using vectors instead. However, it would appear that this is no longer the case: a simple profiling would indicate that this isn’t true:

```racket
#lang typed/racket/base

(struct s ([a : Integer] [b : String]))

(: v (Integer String -> (Vector Integer String)))
(define (v a b)
  (vector a b))

(: random-value (All [a] ((Integer String -> a) -> a)))
(define (random-value make)
  (make (random 1000) (string (integer->char (random 128)))))

(: construct-random-values (All [a] ((Integer String -> a) Nonnegative-Integer -> Void)))
(define (construct-random-values make n)
  (for ([i (in-range n)])
    (random-value make)))

(let ([times 10000000])
  (time (construct-random-values s times))
  (time (construct-random-values v times)))
```

```
cpu time: 2371 real time: 2369 gc time: 15
cpu time: 2297 real time: 2295 gc time: 8
```

Is this still valid in some way that my naïve benchmark doesn’t accommodate for? If it isn’t useful anymore, it should be removed.

**Comment by stamourv** [comment]
It used to be (2012ish) that struct construction was much slower than vector construction.
Then, Matthew improved struct construction performance a lot, but it was still slower than vectors.
I haven't measured since that optimization round a few years ago, but your numbers suggest that even that remaining different is now gone.
I'll investigate a bit more, but it does suggest that that recommendation may not be necessary anymore.

**Comment by stamourv** [comment]
I can confirm, even after stripping out everything except the constructions from the loop, the two are almost indistinguishable. Sometimes structs are even faster (but that's all within the margin of error).
I'll remove that recommendation.
Thanks for the report!
